### ISSUE TITLE
Other ToDo items

### ISSUE THREAD

**Issue by msyk** [INTER-Mediator/INTER-Mediator#89]
**_If you think some of below should be a issue, please make a document for it.**_
- [ ] Documentations, especially English documentations.
- [ ] Generating the page on the server-side initially. Now the IMCake is going on.
- [x] Showing as the alert box when any errors occurred ??
- [ ] FileMaker's Find style database search. To do that, the Record-set feature must be support for context.
- [ ] ~~HTML5's local database supporting.~~
- [ ] Searching in PDFs or any kind of files.

**Comment by msyk** [comment]
"Showing as the alert box when any errors occurred" realize as like:
INTERMediatorLog.errorMessageByAlert = true
INTERMediatorLog.errorMessageOnAlert = "fixed alert message"
